# Permalinks

permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge

# Setup
title:               Coder Blog
tagline:             'A Game Dev - A Coder - A Leader - A Father'
description:         'I am coder'
url:                 https://bonandbo.github.io/devblog/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Diep Tran    
  email:             dieptt88@gmail.com

# Custom vars
version:             1.0.0
cards:             http://cards.bobonbon.io/

